### ISSUE TITLE
wget: command not found with builder `cloudfoundry/cnb:bionic`

### ISSUE THREAD

**Issue by derkoe** [buildpack/docs#68]
**On Page:** [Building your application](/docs/create-buildpack/build-app/)

With the default builder `cloudfoundry/cnb:bionic` selected the following error occurs when running the build:

```
===> BUILDING
[builder] ---> Java Buildpack
[builder] ---> Downloading and extracting OpenJDK
[builder] /cnb/buildpacks/io.github.derkoe.buildpacks.java/0.0.1/bin/build: line 14: wget: command not found
[builder]
[builder] gzip: stdin: unexpected end of file
[builder] tar: Child returned status 1
[builder] tar: Error is not recoverable: exiting now
[builder] Error: failed to build: exit status 2
```

The step works when selecting `cloudfoundry/cnb:cflinuxfs3` as default builder

**Comment by jromero** [comment]
Thank you for reporting this issue. We are in the process of updating the tutorial to use sample builders so that we have a more predictable environment.

If you'd like to take a look at what that looks like it is currently here: 

https://github.com/buildpack/samples/tree/master/buildpacks/ruby-bundler
